# SPDX-FileCopyrightText: 2023 Johannes Krauser III <krauser@hey.com>
#
# SPDX-License-Identifier: CC0-1.0
image:
    file: .gitpod.Dockerfile
tasks:
  - name: Setup
    before: yarn
    init: forge install
    command: yarn compile
